[project]
authors = ["DarthTimothee <timoverlaan@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "LB2292-Lab"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipython = ">=8.32.0,<9"
ipykernel = ">=6.29.5,<7"
pip = ">=25.0,<26"
python = ">=3.13.1,<4"
numpy = ">=2.2.2,<3"
scipy = ">=1.15.1,<2"
matplotlib = ">=3.10.0,<4"
scikit-learn = ">=1.6.1,<2"
statsmodels = ">=0.14.4,<0.15"
